import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#151714',
    textMuted: '#6F746D',
    textSubtle: '#93978F',
    background: '#F7F6F1',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    surfaceMuted: '#F2F3EE',
    accent: '#FFC83D',
    accentSoft: '#FFF3C6',
    onAccent: '#151714',
    mint: '#E5F3EB',
    mintStrong: '#4D9B78',
    border: '#E7E8E2',
    borderStrong: '#D4D8D1',
    danger: '#E65E58',
    success: '#4D9B78',
    icon: '#61665F',
    tabIconDefault: '#737970',
    tabIconSelected: '#151714',
    tint: '#4D9B78',
    overlay: '#151714',
    captionSurface: 'rgba(0, 0, 0, 0.4)',
    captionText: '#FFFFFF',
    shadow: '#151714',
    mapBackground: '#EDF1EA',
    mapRoad: '#FFFFFF',
    imageFallback: '#DADFD7',
  },
  dark: {
    text: '#F3F5F0',
    textMuted: '#ADB5AC',
    textSubtle: '#858D85',
    background: '#101310',
    surface: '#181C18',
    surfaceElevated: '#20251F',
    surfaceMuted: '#252A24',
    accent: '#F4BF38',
    accentSoft: '#3B3218',
    onAccent: '#171A16',
    mint: '#1D3329',
    mintStrong: '#74B696',
    border: '#2E352E',
    borderStrong: '#3C453C',
    danger: '#FF8179',
    success: '#74B696',
    icon: '#B5BDB3',
    tabIconDefault: '#8D968C',
    tabIconSelected: '#F3F5F0',
    tint: '#74B696',
    overlay: '#101310',
    captionSurface: 'rgba(0, 0, 0, 0.4)',
    captionText: '#FFFFFF',
    shadow: '#000000',
    mapBackground: '#1A211C',
    mapRoad: '#2E372F',
    imageFallback: '#2B332C',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
  },
});
